# Server settings  
server:  
    port: 81
    address: localhost  
  
# DATASOURCE  
jdbc:  
    driverClass: com.mysql.jdbc.Driver  
    url: jdbc:mysql://115.28.158.206:3306/realityMgr?useUnicode=true&characterEncoding=utf-8  
    username: realitymgr 
    password: realitymgradmin
  
# SPRING PROFILES  
spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  
    # data source
    mvc.view:
        prefix: /front/
        suffix: .jsp
          
# MyBatis  
mybatis:  
    typeAliasesPackage: com.work.bean 
    mapperLocations: classpath:/**/mapper/xml/*.xml  
    configLocation: classpath:/mybatis-config.xml  
  
# LOGGING  
logging:  
    level:  
       com.ibatis: DEBUG